version: '3'

services:
  app:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app:z
    ports:
      - "3000:3000"
    command: "npm run dev"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: comfy-backend
    volumes:
      - ./.pgdata:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
